-- 코드를 입력하세요
-- 자동차 종류가 '세단' 또는 'SUV' 
--  2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 대여 금액을 기준으로 내림차순
-- 자동차 종류를 기준으로 오름차순 정렬
-- 자동차 ID를 기준으로 내림차순

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100)AS FEE
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = P.CAR_TYPE AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND P.DURATION_TYPE='30일 이상'
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV') AND (FEE>=500000 AND FEE<2000000) 
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC