-- 리뷰를 가장 많이 작성한 회원의 리뷰들, 회원 이름, 리뷰 텍스트, 리뷰 작성일
SELECT MEMBER_NAME,REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(REVIEW_TEXT) DESC LIMIT 1
)

ORDER BY REVIEW_DATE,REVIEW_TEXT