-- 코드를 입력하세요
SELECT B.AUTHOR_ID,AUTHOR_NAME,CATEGORY, SUM(SALES * PRICE)AS TOTAL_SALES
FROM BOOK B ,AUTHOR A ,BOOK_SALES S
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = S.BOOK_ID AND DATE_FORMAT(SALES_DATE, '%Y-%m') LIKE '2022-01'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC

