-- 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS,DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') 
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE)= 2022 AND MONTH(B.CREATED_DATE)=10
ORDER BY R.CREATED_DATE, B.TITLE