-- 코드를 입력하세요 
-- 테이블에서 생산일자가 2022년 5월인 식품
-- 식품 ID, 식품 이름, 총매출
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT*P.PRICE)	AS TOTAL_SALES
FROM FOOD_PRODUCT P,FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID AND DATE_FORMAT(PRODUCE_DATE,'%Y-%m') LIKE '2022-05'
GROUP BY P.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC